config/routes.rb
Landmark::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resource :account
  resources :projects do
    resources :flows
    resources :states
    resources :actions
  end

  resources :demos, :only => [:show]

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [] do
        collection do
          get :auth
          get :track
        end

        resources :states do
          collection do
            get :query
          end
        end

        resources :actions do
          collection do
            get :query
            post :query
          end
        end
      end

      resources :flows do
        member do
          get :query
        end

        collection do
          get :current
          post :set_current
        end

        resources :steps, :controller => "flow_steps"
      end

      resources :resources do
        collection do
          get :next_page_actions
        end
      end

      resources :states do
        collection do
          get :query
        end
      end

      resource :graph, :only => [] do
        collection do
          post :layout
        end
      end
    end
  end

  get "/signup" => "home#signup"
  root :to => 'home#index'
end

app/models/state.rb
class State < ActiveRecord::Base
  belongs_to :project
  has_many :source_links, class_name: "StateLink", foreign_key: "target_id"
  has_many :sources, :through => :source_links
  has_many :target_links, class_name: "StateLink", foreign_key: "source_id"
  has_many :targets, :through => :target_links

  validates :name, presence: true  
  validates :name, uniqueness: {scope: :project_id}

  attr_accessible(:name, :expression, :variable, :sources)

  # Generates a partial Sky query for the state change.
  def codegen(options={})
    output = []

    source_condition = nil
    if sources.empty?
      # If there are no sources and no expression then it's a start state.
      if expression.blank?
        source_condition = "state == 0"

      # If there is an expression then just make sure it can't transition from itself.
      else
        source_condition = "state != #{id}"
      end

    # If we have sources then only use those.
    else 
      source_condition = sources.map {|source| "state == #{source.id}"}.join(" || ")
    end

    # The expression should default to "true" if not provided.
    expression_condition = !expression.blank? ? expression : "true"

    # Generate the condition.
    output << "WHEN (#{source_condition}) && (#{expression_condition}) THEN"
    output << "  SET prev_state = state"
    output << "  SET state = #{id}"

    # Set variable when we enter.
    output << "  SET #{variable} = true" unless variable.blank?

    # Inject an after-hook from the caller.
    if options[:after].is_a?(Proc)
      output << options[:after].call(self).to_s.gsub(/^/, "  ")
    elsif options[:after].is_a?(String)
      output << options[:after].gsub(/^/, "  ")
    end

    output << "END"

    return output.join("\n")
  end
end

app/controllers/api/v1/states_controller.rb
module Api::V1
  class StatesController < Api::V1::BaseController
    # GET /projects/:id/states/query
    def query
      return render json: {} if @project.states.empty?

      replay_from = params[:replay_from].to_i
      step = (params[:step] || 1).to_i
      duration = (params[:duration] || 30).to_i
      unit = (params[:unit] || "DAY").to_s.upcase

      # Generate the Sky query.
      query = []
      query << @project.codegen_state_decl
      query << "DECLARE index AS INTEGER"
      query << @project.codegen_states(
        after: lambda {|state|
          out = []
          if state.id == replay_from
            out << "FOR index EVERY #{step} #{unit} WITHIN #{duration} #{unit}"
            out << "  FOR EACH EVENT"
            out << @project.codegen_states(
              after: "SELECT count() AS count GROUP BY index, prev_state, state INTO 'transitions'"
            ).gsub(/^/, "    ")
            out << "  END"
            out << "  SELECT count() AS count GROUP BY index, state INTO 'states'"
            out << "END"
          else
            out << "SELECT count() AS count GROUP BY index, prev_state, state INTO 'transitions'"
          end
          return out.join("\n")
        }
       )
      query = query.join("\n")
      # warn(query)
      results = @project.run_query(query: query)

      # Normalize states.
      states = @project.states.as_json(only: [:id, :name])
      lookup = states.inject({}) {|h,state| h[state["id"]] = state; h}
      if replay_from > 0
        results["states"] = SkyDB.denormalize(results["states"], ["index", "state"])
        SkyDB.normalize(results["states"], ["index"], ["count"]).each do |item|
          state = lookup[item["state"].to_i]
          state["index"] = item["index"] unless state.nil?
        end
      end

      # Normalize transitions into something usable.
      transitions = results["transitions"]
      transitions = SkyDB.denormalize(transitions, ["index", "prev_state", "state"])
      transitions = SkyDB.normalize(transitions, ["index"], ["count"])
      transitions.each do |transition|
        transition["source"] = transition.delete("prev_state")
        transition["target"] = transition.delete("state")
        transition["label"] = transition["weight"] = transition["index"].values.first["count"]
      end
      transitions.reject! {|transition| transition["source"] == "0" || transition["target"] == "0"}

      # Generate the layout.
      width, height = generate_layout(states, transitions)
      json = {
        width: width,
        height: height,
        states: states,
        transitions: transitions,
      }
      if replay_from > 0
        json[:replay] = {
            id: replay_from,
            step: step,
            duration: duration,
            unit: unit,
          }
      end
      render :json => json
    end


    private

    # Generates the layout using graphviz.
    def generate_layout(states, transitions)
      states.each {|s| s["label"] = s["name"]}

      graph = Miniviz::Graph.new(nodes:states, edges:transitions)
      graph.rankdir = "LR"
      graph.fontname = "Helvetica"
      graph.fontsize = 14
      errors = graph.layout()
      graph.apply_layout()

      states.each {|s| s.delete("label")}

      return graph.width, graph.height
    end
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_filter :authenticate_user!
  before_filter lambda{ find_project(params[:project_id]); true  }
  before_filter :normalize_params
  respond_to :html

  # GET /projects/:project_id/states
  def index
    @states = @project.states
  end

  # GET /projects/:project_id/states/new
  def new
    @state = @project.states.build
  end

  # POST /projects/:project_id/states
  def create
    @state = @project.states.build(params[:state])
    if @state.save
      redirect_to(project_states_path(@project), :notice => 'State was successfully created.')
    else
      render :action => "new"
    end
  end

  # GET /projects/:project_id/states/:id/edit
  def edit
    @state = @project.states.find(params[:id])
  end

  # POST /projects/:project_id/states/:id
  def update
    @state = @project.states.find(params[:id])
    if @state.update_attributes(params[:state])
      redirect_to(project_states_path(@project), :notice => 'State was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /projects/:project_id/states/:id/destroy
  def destroy
    @state = @project.states.find(params[:id])
    @state.destroy()
    redirect_to(project_states_path(@project), :notice => 'State was successfully removed.')
  end

  private

  def normalize_params
    return if params[:state].nil?
    
    sources = params[:state]["sources"]
    if sources
      sources.reject! {|id| id.blank?}
      sources.map! {|id| @project.states.find(id)}
      params[:state]["sources"] = sources
    end
  end
end

app/views/states/_form.html.erb
<%= form_for [@project, @state] do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :variable, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :variable, :class => "input-xlarge" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :expression, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :expression, :class => "input-xlarge", style: "height:80px" %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :sources, "Source States", :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :sources, State.all, :id, :name, {selected: @state.sources.map{|s| s.id}}, multiple: true, class: "chosen-select", style: "width:280px", "data-placeholder" => " " %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit(:class => 'btn btn-primary btn-embossed') %>
      <%= link_to('Back', :back, :class => 'btn btn-inverse btn-embossed') %>
    </div>
  </div>
<% end %>

app/views/states/edit.html.erb
<div class="row" style="padding: 0 32px; margin-top:20px">
  <div class="span12">
    <h3>Edit State</h3>
    
    <%= render 'form' %>
  </div>
</div>

app/views/states/index.html.erb
<div id="states" class="row" style="padding: 0 32px; margin-top:20px">
  <div class="span12">
    <h3 style="display: inline">User States</h3>

    <div class="pull-right">
      <div class="btn-toolbar">
        <div class="btn-group">
          <%= link_to(new_project_state_path(@project), class:"btn btn-primary", title:"Add State") do %>
            <i class="fui-plus-inverted"></i>
          <% end %>
        </div>
      </div>
    </div>

    <div class="pull-right">
      <div id="replay-toolbar" class="btn-toolbar" style="margin-right:20px">
        <div class="btn-group">
          <%= link_to("Replay:", '#', class:"btn btn-warning disabled", style:"color:white") %>
          <%= link_to('#', id:"replay-play", class:"btn btn-warning", title:"Replay State Transitions") do %>
            <i class="fui-play"></i>
          <% end %>
          <%= link_to('#', id:"replay-close", class:"btn btn-warning", title:"Turn Off Replay") do %>
            <i class="fui-cross"></i>
          <% end %>
        </div>
      </div>
    </div>

    <% if @project.states.count == 0 %>
      <p>It doesn't look like you've set up any user states yet.</p>

    <% else %>
      <div id="chart"></div>
    <% end %>
  </div>
</div>

<script>
  $(function() {
    landmark.state.initialize(<%= @project.id %>);
  })
</script>

app/views/states/new.html.erb
<div class="row" style="padding: 0 32px; margin-top:20px">
  <div class="span12">
    <h3>New State</h3>
    <p>States represent where a user is in their lifecycle based on their events and past state.</p>
    
    <%= render 'form' %>
  </div>
</div>