config/routes.rb
Landmark::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resource :account
  resources :projects do
    resources :flows
    resources :states
    resources :actions
  end

  resources :demos, :only => [:show]

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [] do
        collection do
          get :auth
          get :track
        end

        resources :states do
          collection do
            get :query
          end
        end

        resources :actions do
          collection do
            get :query
            post :query
          end
        end
      end

      resources :flows do
        member do
          get :query
        end

        collection do
          get :current
          post :set_current
        end

        resources :steps, :controller => "flow_steps"
      end

      resources :resources do
        collection do
          get :next_page_actions
        end
      end

      resources :states do
        collection do
          get :query
        end
      end

      resource :graph, :only => [] do
        collection do
          post :layout
        end
      end
    end
  end

  get "/signup" => "home#signup"
  root :to => 'home#index'
end

app/views/resources/show.html.erb
<div class="row" style="padding: 0 32px;">
  <div class="span12">
    <h3><%= @resource.uri %></h3>

    <div class="row">
      <div class="span6">
        <h4>Next Pages</h4>      
        <table class="table table-striped table-hover">
          <tbody>
              <% @next_pages.each do |page_view| %>
                <tr>
                  <td><%= link_to(page_view[:uri], project_resource_path(@project, page_view[:resource].slug)) %></td>
                  <td><%= page_view[:count] %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>