config/routes.rb
Landmark::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resource :account
  resources :projects do
    resources :flows
    resources :states
    resources :actions
  end

  resources :demos, :only => [:show]

  namespace :api do
    namespace :v1 do
      resources :projects, :only => [] do
        collection do
          get :auth
          get :track
        end

        resources :states do
          collection do
            get :query
          end
        end

        resources :actions do
          collection do
            get :query
            post :query
          end
        end
      end

      resources :flows do
        member do
          get :query
        end

        collection do
          get :current
          post :set_current
        end

        resources :steps, :controller => "flow_steps"
      end

      resources :resources do
        collection do
          get :next_page_actions
        end
      end

      resources :states do
        collection do
          get :query
        end
      end

      resource :graph, :only => [] do
        collection do
          post :layout
        end
      end
    end
  end

  get "/signup" => "home#signup"
  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landmark</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield(:head) %>
  <%= csrf_meta_tags %>
  
  <% if !@project.nil? %>
    <script>
      landmark.projectId = <%= @project.id %>
    </script>
  <% end %>
</head>
<body>

<div class="navbar header">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-01">
      </button>
      <%= link_to('Landmark', root_path, :class => 'brand')%>

      <div class="nav-collapse collapse" id="nav-collapse-01">
        <% if user_signed_in? %>
          <ul class="nav">
            <li class="<%= request.path.index(/\/projects\/\d+$/) == 0 ? 'active' : '' %>">
              <%= link_to('Home', project_path(current_project)) %>
            </li>
            <!--
            <li class="<%= request.path.index(/\/projects\/\d+\/states/) == 0 ? 'active' : '' %>">
              <%= link_to('User States', project_states_path(current_project)) %>
            </li>
            -->
            <li class="<%= request.path.index(/\/projects\/\d+\/actions/) == 0 ? 'active' : '' %>">
              <%= link_to('User Actions', project_actions_path(current_project)) %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Settings <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to('Account', account_path) %></li>
                <li><%= link_to('Projects', projects_path) %></li>
              </ul>
            </li>
            <li class="<%= request.path.index('/help') == 0 ? 'active' : '' %>">
              <%= link_to('Help', page_path("help")) %>
            </li>
            <li><%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %></li>
          </ul>

          <% if current_project.name == 'verizon' %>
            <div class="pull-right">
              <img src="/assets/misc/vzw.png" style="margin-right:30px; padding-top:8px"/>
            </div>
          <% elsif current_account.projects.count > 1 %>
            <div class="btn-group pull-right" style="margin-right:20px; padding-top:15px">
                <i class="dropdown-toggle dropdown-toggle-inverse"></i>
                <button class="btn btn-warning btn-small"><%= current_project.public_name %></button>
                <button class="btn btn-warning btn-small dropdown-toggle" data-toggle="dropdown">
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-inverse">
                  <% current_account.projects.order(:name).each do |project| %>
                    <li><%= link_to(project.public_name, project_path(project))%></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--
<% if !notice.blank? %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if !alert.blank? %>
  <p class="alert"><%= alert %></p>
<% end %>
-->

<%= yield %>

</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Landmark - Behavioral Analytics</title>
  <%= stylesheet_link_tag    "public", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Francois+One,Lato:300,400,700,900,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "public" %>
  <%= yield(:head) %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <!-- begins navbar -->
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand scroller" data-section="body" href="index.html">
            <img src="img/icon-landmark.png" alt="logo" />
            Landmark
        </a>
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <li><%= link_to('Sign in', new_user_session_path) %></li>
            <li><%= link_to('Sign up', '/users/sign_up') %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- ends navbar -->

  <%= yield %>
</body>
</html>